
#ifndef RPP_ERRORCODE_H
#define RPP_ERRORCODE_H

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_NOPHY_FOUND,
    RPP_APP_PHYNOT_READY,
    RPP_APP_UNDEFINED_ERROR
}eGetPhyErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_UNSUPPORTED_REGULATORY,
    RPP_APP_UNSUPPORTED_FREQBAND,
    RPP_APP_UNSUPPORTED_SPATIALSTREAMS,
    RPP_APP_UNSUPPORTED_RATESETTING,
    RPP_APP_UNSUPPORTED_HTMCSSETTING,
    RPP_APP_UNSUPPORTED_VHTMCSSETTING,
    RPP_APP_UNSUPPORTED_AMSDUDEPTH,
    RPP_APP_UNSUPPORTED_AMPDUDEPTH,
    RPP_APP_UNDEFINED_ERROR
}eSetPhyErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_INVALID_MACADDR,
    RPP_APP_INVALID_SSID,
    RPP_APP_INVALID_BSSID,
    RPP_APP_INVALID_EXTRADATALEN,
    RPP_APP_UNSUPPORTED_HTMCSSETTING,
    RPP_APP_UNSUPPORTED_VHTMCSSETTING,
    RPP_APP_UNSUPPORTED_AMSDUDEPTH,
    RPP_APP_UNSUPPORTED_AMPDUDEPTH,
    RPP_APP_UNDEFINED_ERROR
}eAddStaErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_INVALID_STAHANDLE,
    RPP_APP_UNDEFINED_ERROR
}eDelStaErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_INVALID_STAHANDLE,
    RPP_APP_UNDEFINED_ERROR
}eAssocErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_INVALID_STAHANDLE,
    RPP_APP_STATION_NOTASSOCIATED,
    RPP_APP_UNDEFINED_ERROR
}eDeAssocErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_INVALID_STAHANDLE,
    RPP_APP_STATION_NOTASSOCIATED,
    RPP_APP_ASSOCIATED_TOAP,
    RPP_APP_INVALID_BSS,
    RPP_APP_UNDEFINED_ERROR
}eFastBSSTransitErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_UNKNOWN_ERROR,
    RPP_APP_AP_NOTFOUND,
    RPP_APP_MAYBE_INCORRECTPWD,
    RPP_APP_HANDSHAKE_TIMEOUT,
    RPP_APP_CONNECT_FAIL,
    RPP_APP_UNDEFINED_ERROR
}eSetModeErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_INVALID_STAHANDLE,
    RPP_APP_UNDEFINED_ERROR
}eGetStaStatsErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_INVALID_PHYHANDLE,
    RPP_APP_INVALID_STAHANDLE,
    RPP_APP_UNDEFINED_ERROR
}eClrStaStatsErrorCode;

typedef enum {
    RPP_APP_GETPHY_SUCCESS = 0,
    RPP_APP_UNDEFINED_ERROR
}eSetLogLevelReqErrorCode;

#endif /* RPP_ERRORCODE_H */
